name: clear-cache

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      
    - name: Build
      uses: ./.github/workflows/flutter-build.yml
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ./flutter-apk
